In [1]:
# Tutorial number 1
# Importing Library
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])
print(a)

[0 1 2 3]


In [3]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# python list
%timeit [i**2 for i in range(1000)]

835 µs ± 13.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
# Numpy list
%timeit np.arange(1000)**2

15.9 µs ± 582 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [6]:
# 1-D array
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
# a-Dimentional
a.ndim

1

In [8]:
a.shape

(3,)

In [9]:
len(a)

3

In [10]:
# 2-D array
b = np.array([[0,1,2], [3,4,5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
# b-Dimensional
b.ndim

2

In [12]:
b.shape

(2, 3)

In [13]:
len(b[0])

3

In [14]:
# 3-D array
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [15]:
# Getting dimensions
c.ndim

3

In [16]:
# using shape function
c.shape

(2, 2, 2)

In [17]:
# using len function
len(c)

2

In [18]:
# Len function
len(c[0])

2

In [19]:
# Tutorial number 2
# Using linspace
l = np.linspace(1, 10, 29) # Start, End, linspace
l

array([ 1.        ,  1.32142857,  1.64285714,  1.96428571,  2.28571429,
        2.60714286,  2.92857143,  3.25      ,  3.57142857,  3.89285714,
        4.21428571,  4.53571429,  4.85714286,  5.17857143,  5.5       ,
        5.82142857,  6.14285714,  6.46428571,  6.78571429,  7.10714286,
        7.42857143,  7.75      ,  8.07142857,  8.39285714,  8.71428571,
        9.03571429,  9.35714286,  9.67857143, 10.        ])

In [20]:
# Common array function 
one = np.ones((3,3,4))
one

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [21]:
two = np.zeros((2,4,3,4))
two

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [22]:
# Identity Matrices
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
i = np.eye(2,3)
i

array([[1., 0., 0.],
       [0., 1., 0.]])

In [24]:
print(type(i))

<class 'numpy.ndarray'>


In [25]:
# Tutorial number 3
# Create array using diagonal function 
diagonal = np.diag([1,2,3,4])
diagonal

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
np.diag(diagonal)

array([1, 2, 3, 4])

In [27]:
rand = np.random.rand(4)
rand

array([0.44125358, 0.93528804, 0.95566412, 0.27168643])

In [28]:
randn = np.random.randn(5)
randn

array([ 0.85888042,  0.03228886,  0.82004685, -0.17199725, -1.67185996])

In [29]:
randn.dtype

dtype('float64')

In [30]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [31]:
a.dtype

dtype('int32')

In [32]:
n = np.arange(4, dtype='int64')
n

array([0, 1, 2, 3], dtype=int64)

In [33]:
n = np.zeros((3,3), dtype='int')
n

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [34]:
n.dtype

dtype('int32')

In [35]:
a = np.array([1+2j, 3+4j])
a

array([1.+2.j, 3.+4.j])

In [36]:
a.dtype

dtype('complex128')

In [37]:
a = np.array([True, False, True, False])
a

array([ True, False,  True, False])

In [38]:
a.dtype

dtype('bool')

In [39]:
# Indexing the numpy array
a = np.arange(10)
a[5]

5

In [40]:
d = np.diag([1,2,3])
d

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [41]:
d[1,1]

2

In [42]:
# Assigning Value
d[1,1] = 3

In [43]:
d

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [44]:
d = np.arange(10)

In [45]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
d[1:10:2]

array([1, 3, 5, 7, 9])

In [47]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
a[5:] = 123
a

array([  1,   2,   3,   4,   5, 123, 123, 123, 123, 123])

In [49]:
a = a[::-1]
a

array([123, 123, 123, 123, 123,   5,   4,   3,   2,   1])

In [50]:
a = a[::-1]
a

array([  1,   2,   3,   4,   5, 123, 123, 123, 123, 123])

In [51]:
# Tutorial Number 4
# Copies and views
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [52]:
b = a[::2]
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
np.shares_memory(a,b)

True

In [54]:
b[0] = 10
b

array([10,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [55]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [56]:
c = a[::-2].copy()
c

array([19, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [57]:
c[0] = 0
c

array([ 0, 17, 15, 13, 11,  9,  7,  5,  3,  1])

In [58]:
a, b, c

(array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]),
 array([10,  2,  4,  6,  8, 10, 12, 14, 16, 18]),
 array([ 0, 17, 15, 13, 11,  9,  7,  5,  3,  1]))

In [59]:
# Fancy indexing
randomint = np.random.randint(0, 20, 15)
randomint

array([ 4, 12, 14,  7,  2, 19,  8, 14,  3, 16, 15,  9, 16,  2,  1])

In [60]:
mask = (randomint % 2 == 0)
[mask for mask in mask if mask == True]

[True, True, True, True, True, True, True, True, True]

In [61]:
a = randomint[mask]
a

array([ 4, 12, 14,  2,  8, 14, 16, 16,  2])

In [62]:
randomint[mask] = -1
randomint

array([-1, -1, -1,  7, -1, 19, -1, -1,  3, -1, 15,  9, -1, -1,  1])

In [63]:
# Indexing with an integer
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
a[[1,2,3,4,5]]

array([10, 20, 30, 40, 50])

In [65]:
a[[1,2,3,4,5]] = 1
a

array([ 0,  1,  1,  1,  1,  1, 60, 70, 80, 90])

In [66]:
# Element wise operator
a = np.arange(1, 100, 5)
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [67]:
a + 2

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78, 83,
       88, 93, 98])

In [68]:
a

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [69]:
a**2

array([   1,   36,  121,  256,  441,  676,  961, 1296, 1681, 2116, 2601,
       3136, 3721, 4356, 5041, 5776, 6561, 7396, 8281, 9216], dtype=int32)

In [70]:
a = np.array([2,2,2,2])
b = np.zeros(4, dtype='int') + 2

In [71]:
a, b

(array([2, 2, 2, 2]), array([2, 2, 2, 2]))

In [72]:
a - b

array([0, 0, 0, 0])

In [73]:
a+b

array([4, 4, 4, 4])

In [74]:
a*b

array([4, 4, 4, 4])

In [75]:
a**b

array([4, 4, 4, 4], dtype=int32)

In [76]:
# Matrix multiplication
c = np.diag([1,2,3,4])
c

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [77]:
print(c*c)
print('*****************************')
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
*****************************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [78]:
# Comparison
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
a == b

array([ True,  True,  True,  True])

In [79]:
a>b

array([False, False, False, False])

In [80]:
a<b

array([False, False, False, False])

In [81]:
a==b

array([ True,  True,  True,  True])

In [82]:
# Array-wise comparision
np.array_equal(a, b)

True

In [83]:
# Logical Operations
np.logical_or(a, b)

array([ True,  True,  True,  True])

In [84]:
np.logical_and(a,b)

array([ True,  True,  True,  True])

In [85]:
np.logical_not(a,b)

array([0, 0, 0, 0])

In [86]:
# Transcendental Operators
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [87]:
np.sin(b)

array([0., 0., 0., 0.])

In [88]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [89]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [90]:
# Shape Matching
a = np.array([1,2,3,4])
b = np.array([1,2])
# a+b  # This will give the error because when we add the two array, they must have same dimensions

In [91]:
# Basic reduction
# Computing sum
a = np.array([1,2,3,4])
a.sum()
np.sum(a)

10

In [92]:
n = np.array([[1,2], [3,4]])
n

array([[1, 2],
       [3, 4]])

In [93]:
n.sum(axis=0)

array([4, 6])

In [94]:
n.sum(axis=1)

array([3, 7])

In [95]:
# Other Reduction
n = np.array([1,2,3,4])
m = np.array([[2,3,4,5], [4,5,6,7]])
m

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [96]:
n.min()

1

In [97]:
n.max()

4

In [98]:
n.argmin()

0

In [99]:
n.argmax()

3

In [100]:
n.all()

True

In [101]:
n.any()

True

In [102]:
np.all([True, False])

False

In [103]:
np.any([True, False, True])

True

In [104]:
np.all((n != m))

True

In [105]:
np.all(a == b)

<ipython-input-105-f5a08c362170>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  np.all(a == b)


False

In [106]:
# Statistics
n.mean()

2.5

In [107]:
m.mean()

4.5

In [108]:
np.median(n)

2.5

In [109]:
np.median(m, axis=-1)

array([3.5, 5.5])

In [110]:
np.mean(m, axis=-1)

array([3.5, 5.5])

In [111]:
np.std(n)

1.118033988749895

In [112]:
n.std()

1.118033988749895

In [113]:
n.T

array([1, 2, 3, 4])

In [114]:
m.T

array([[2, 4],
       [3, 5],
       [4, 6],
       [5, 7]])

In [115]:
m = m.T

In [116]:
m.std(axis=0)

array([1.11803399, 1.11803399])

In [117]:
m.argmax(axis=0)

array([3, 3], dtype=int64)

In [118]:
# Broadcasting of Matrix
a = np.tile(np.arange(0, 40, 10), (3, 1))
a.shape

(3, 4)

In [119]:
a = a.T
a.shape

(4, 3)

In [120]:
b = np.array([1,2,3])
print(b.shape)


(3,)


In [121]:
a + b

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [122]:
b = b[:, np.newaxis]
print(b.shape)

(3, 1)


In [123]:
# Flattening
# Converting 2-D array into 1-D array
a = np.array([[1,2,1], [1,2,1]])
print(a.ndim)
a.shape

2


(2, 3)

In [124]:
a.ravel()

array([1, 2, 1, 1, 2, 1])

In [125]:
a.ndim

2

In [126]:
a = a.T
a

array([[1, 1],
       [2, 2],
       [1, 1]])

In [127]:
print(a.shape)

(3, 2)


In [128]:
b = a.T.ravel()
b

array([1, 2, 1, 1, 2, 1])

In [129]:
# Reshaping
b = b.reshape((3,2))
print(b)
print(b.shape)

[[1 2]
 [1 1]
 [2 1]]
(3, 2)


In [130]:
b[0, 0] = 100
b

array([[100,   2],
       [  1,   1],
       [  2,   1]])

In [131]:
a

array([[100,   1],
       [  2,   2],
       [  1,   1]])

In [132]:
# Be aware, reshape may also returns a copy
a = np.zeros((3, 2))
a.shape

(3, 2)

In [133]:
b = np.ones(3*2)
b.shape

(6,)

In [134]:
# Changing Dimensions
z = np.array([1,2,1])
z[:, np.newaxis]

array([[1],
       [2],
       [1]])

In [135]:
# Dimension Shuffeling

a = np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [136]:
a.reshape((4,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [137]:
# Resizing the matrix
a = np.arange(4)
a.shape

(4,)

In [138]:
np.resize(a, (8,)).shape

(8,)

In [139]:
# Sorting Data

a = np.array([[1,2,2], [5,3,2]])
a

array([[1, 2, 2],
       [5, 3, 2]])

In [140]:
b = np.sort(a, axis=1)
b

array([[1, 2, 2],
       [2, 3, 5]])

In [141]:
a.sort(axis=1)
a

array([[1, 2, 2],
       [2, 3, 5]])

In [142]:
# Fancy Sorting
a = np.array([1,6,2,56,2,6,2,7,2,7,23,0,34,7,2,53,76,234])
a.shape

(18,)

In [143]:
b = np.argsort(a)
b

array([11,  0, 14,  6,  8,  2,  4,  5,  1,  7,  9, 13, 10, 12, 15,  3, 16,
       17], dtype=int64)

In [144]:
a[b]

array([  0,   1,   2,   2,   2,   2,   2,   6,   6,   7,   7,   7,  23,
        34,  53,  56,  76, 234])

In [145]:
for i in a[b]:
    print(i)

0
1
2
2
2
2
2
6
6
7
7
7
23
34
53
56
76
234
